package net.haesleinhuepf.clijx.codegenerator;

import net.haesleinhuepf.clij.advancedfilters.*;
import net.haesleinhuepf.clij.advancedmath.*;
import net.haesleinhuepf.clij.clij1wrappers.*;
import net.haesleinhuepf.clij.io.PreloadFromDisc;
import net.haesleinhuepf.clij.io.ReadImageFromDisc;
import net.haesleinhuepf.clij.io.ReadRawImageFromDisc;
import net.haesleinhuepf.clij.kernels.Kernels;
import net.haesleinhuepf.clij.matrix.*;
import net.haesleinhuepf.clij.painting.DrawBox;
import net.haesleinhuepf.clij.painting.DrawLine;
import net.haesleinhuepf.clij.painting.DrawSphere;
import net.haesleinhuepf.clij.painting.DrawTwoValueLine;
import net.haesleinhuepf.clij.piv.FastParticleImageVelocimetry;
import net.haesleinhuepf.clij.piv.ParticleImageVelocimetry;
import net.haesleinhuepf.clij.piv.ParticleImageVelocimetryTimelapse;
import net.haesleinhuepf.clij.registration.DeformableRegistration2D;
import net.haesleinhuepf.clij.registration.TranslationRegistration;
import net.haesleinhuepf.clij.registration.TranslationTimelapseRegistration;

public interface CLIJ2Plugins {
    public Class[] classes = {
            CLIJ1Absolute.class,
            CLIJ1Mask.class,
            CLIJ1AddImageAndScalar.class,
            CLIJ1MaskStackWithPlane.class,
            CLIJ1AddImages.class,
            CLIJ1MaximumBox.class,
            CLIJ1AddImagesWeighted.class,
            CLIJ1MaximumIJ.class,
            CLIJ1AffineTransform2D.class,                      
            CLIJ1MaximumImageAndScalar.class,
            CLIJ1AffineTransform3D.class,                      
            CLIJ1MaximumImages.class,
            CLIJ1AffineTransform.class,
            CLIJ1MaximumOfAllPixels.class,
            CLIJ1ApplyVectorfield.class,                       
            CLIJ1MaximumSliceBySliceSphere.class,
            CLIJ1ArgMaximumZProjection.class,                  
            CLIJ1MaximumSphere.class,
            CLIJ1AutomaticThreshold.class,                     
            CLIJ1MaximumXYZProjection.class,
            CLIJ1BinaryAnd.class,                              
            CLIJ1MaximumZProjection.class,
            CLIJ1BinaryNot.class,                              
            CLIJ1MeanBox.class,
            CLIJ1BinaryOr.class,                               
            CLIJ1MeanIJ.class,
            CLIJ1BinaryXOr.class,                              
            CLIJ1MeanSliceBySliceSphere.class,
            CLIJ1Blur.class,                                   
            CLIJ1MeanSphere.class,
            CLIJ1BlurSliceBySlice.class,                       
            CLIJ1MeanZProjection.class,
            CLIJ1CenterOfMass.class,                           
            CLIJ1MedianBox.class,
            CLIJ1ConvertToImageJBinary.class,                  
            CLIJ1MedianSliceBySliceBox.class,
            CLIJ1Copy.class,                                   
            CLIJ1MedianSliceBySliceSphere.class,
            CLIJ1CopySlice.class,
            CLIJ1MedianSphere.class,
            CLIJ1CountNonZeroPixelsLocally.class,
            CLIJ1MinimumBox.class,
            CLIJ1CountNonZeroPixelsLocallySliceBySlice.class,
            CLIJ1MinimumIJ.class,
            CLIJ1CountNonZeroVoxelsLocally.class,
            CLIJ1MinimumImageAndScalar.class,
            CLIJ1Crop.class,
            CLIJ1MinimumImages.class,
            CLIJ1DetectMaximaBox.class,
            CLIJ1MinimumOfAllPixels.class,
            CLIJ1DetectMaximaSliceBySliceBox.class,
            CLIJ1MinimumSliceBySliceSphere.class,
            CLIJ1DetectMinimaBox.class,
            CLIJ1MinimumSphere.class,
            CLIJ1DetectMinimaSliceBySliceBox.class,
            CLIJ1MinimumZProjection.class,
            CLIJ1DetectOptima.class,
            CLIJ1MultiplyImageAndCoordinate.class,
            CLIJ1DetectOptimaSliceBySlice.class,
            CLIJ1MultiplyImageAndScalar.class,
            CLIJ1DifferenceOfGaussian.class,
            CLIJ1MultiplyImages.class,
            CLIJ1DifferenceOfGaussianSliceBySlice.class,
            CLIJ1MultiplySliceBySliceWithScalars.class,
            CLIJ1DilateBox.class,
            CLIJ1MultiplyStackWithPlane.class,
            CLIJ1DilateBoxSliceBySlice.class,
            CLIJ1Power.class,
            CLIJ1DilateSphere.class,
            CLIJ1RadialProjection.class,
            CLIJ1DilateSphereSliceBySlice.class,
            CLIJ1ResliceBottom.class,
            CLIJ1DivideImages.class,
            CLIJ1ResliceLeft.class,
            CLIJ1Downsample.class,
            CLIJ1ResliceRight.class,
            CLIJ1DownsampleSliceBySliceHalfMedian.class,
            CLIJ1ResliceTop.class,
            CLIJ1ErodeBox.class,
            CLIJ1RotateLeft.class,
            CLIJ1ErodeBoxSliceBySlice.class,
            CLIJ1RotateRight.class,
            CLIJ1ErodeSphere.class,
            CLIJ1Set.class,
            CLIJ1ErodeSphereSliceBySlice.class,
            CLIJ1SplitStack.class,
            CLIJ1FillHistogram.class,
            CLIJ1SubtractImages.class,
            CLIJ1Flip.class,
            CLIJ1Subtract.class,
            CLIJ1GradientX.class,
            CLIJ1SumPixels.class,
            CLIJ1GradientY.class,
            CLIJ1SumPixelsSliceBySlice.class,
            CLIJ1GradientZ.class,
            CLIJ1SumZProjection.class,
            CLIJ1Histogram.class,
            CLIJ1TenengradFusion.class,
            CLIJ1Invert.class,
            CLIJ1TenengradWeightsSliceBySlice.class,
            CLIJ1LocalThreshold.class,
            CLIJ1Threshold.class,
            BinaryUnion.class,
            BinaryIntersection.class,
            ConnectedComponentsLabeling.class,
            CountNonZeroPixels.class,
            CrossCorrelation.class,
            DifferenceOfGaussian2D.class,
            DifferenceOfGaussian3D.class,
            Extrema.class,
            LocalExtremaBox.class,
            LocalID.class,
            MaskLabel.class,
            MeanClosestSpotDistance.class,
            MeanSquaredError.class,
            MedianZProjection.class,
            NonzeroMinimumDiamond.class,
            Paste2D.class,
            Paste3D.class,
            Presign.class,
            SorensenDiceJaccardIndex.class,
            StandardDeviationZProjection.class,
            StackToTiles.class,
            SubtractBackground2D.class,
            SubtractBackground3D.class,
            TopHatBox.class,
            TopHatSphere.class,
            Exponential.class,
            Logarithm.class,
            GenerateDistanceMatrix.class,
            ShortestDistances.class,
            SpotsToPointList.class,
            TransposeXY.class,
            TransposeXZ.class,
            TransposeYZ.class,
            FastParticleImageVelocimetry.class,
            ParticleImageVelocimetry.class,
            ParticleImageVelocimetryTimelapse.class,
            DeformableRegistration2D.class,
            TranslationRegistration.class,
            TranslationTimelapseRegistration.class,
            SetWhereXequalsY.class,
            Laplace.class,
            Image2DToResultsTable.class,
            WriteValuesToPositions.class,
            GetSize.class,
            MultiplyMatrix.class,
            MatrixEqual.class,
            PowerImages.class,
            Equal.class,
            GreaterOrEqual.class,
            Greater.class,
            Smaller.class,
            SmallerOrEqual.class,
            NotEqual.class,
            ReadImageFromDisc.class,
            ReadRawImageFromDisc.class,
            PreloadFromDisc.class,
            EqualConstant.class,
            GreaterOrEqualConstant.class,
            GreaterConstant.class,
            SmallerConstant.class,
            SmallerOrEqualConstant.class,
            NotEqualConstant.class,
            DrawBox.class,
            DrawLine.class,
            DrawSphere.class,
            ReplaceIntensity.class,
            BoundingBox.class,
            MinimumOfMaskedPixels.class,
            MaximumOfMaskedPixels.class,
            MeanOfMaskedPixels.class,
            LabelToMask.class,
            NClosestPoints.class,
            GaussJordan.class,
            StatisticsOfLabelledPixels.class,
            VarianceOfAllPixels.class,
            StandardDeviationOfAllPixels.class,
            ExcludeLabelsOnEdges.class,
            BinarySubtract.class,
            BinaryEdgeDetection.class,
            DistanceMap.class,
            PullAsROI.class,
            NonzeroMaximumDiamond.class,
            OnlyzeroOverwriteMaximumDiamond.class,
            OnlyzeroOverwriteMaximumBox.class,
            GenerateTouchMatrix.class,
            DetectLabelEdges.class,
            StopWatch.class,
            CountTouchingNeighbors.class,
            ReplaceIntensities.class,
            DrawTwoValueLine.class,
            AverageDistanceOfNClosestPoints.class,
            SaveAsTIF.class

    };

}
